<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="Login"
    errors="1" failures="0" hostname="" id="" package="Login" skipped="0"
    tests="1" time="1.934" timestamp="Fri, 07 Apr 2017 10:59:34 GMT">
  
    <testcase name="Login to Creighton Home page" classname="Login" time="1.934" assertions="0">
    </testcase>
      <system-err>
          Error while running [Dashboard Test / Click on Classes]:

  Error: Invalid URL: You must either add a url property to &quot;DashboardPage&quot; or provide a url as an argument
    at Object.navigate (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\lib\page-object\page.js:58:13)
    at Object.Click on Classes (D:\NightWatch\tests\DashboardTest.js:7:15)
    at Module.call (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:604:44
    at runSingle (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
  Error while running [Login / Login to Creighton Home page]:

  TypeError: creighton.navigate is not a function
    at Object.Login to Creighton Home page (D:\NightWatch\tests\Login.js:8:15)
    at Module.call (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:604:44
    at runSingle (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\aankathi\AppData\Roaming\npm\node_modules\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
      </system-err>
  
  
  </testsuite>
</testsuites>
